### ISSUE TITLE
Milestone에 대한 API 를 구현한다.

### ISSUE THREAD

**Issue by tksrl0379** [boostcamp-2020/IssueTracker-7#7]
# Milestone에 대한 API 를 구현한다.

### Milestone - 전체 Milestone에 대한 CRUD
|메소드|경로|설명|링크|
|-|-|-|-|
|GET	|api/milestone|milestone 불러오기|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#%EC%A0%84%EC%B2%B4-milestone-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0)
|POST	|api/milestone|milestone 생성|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#milestone-%EC%83%9D%EC%84%B1)
|PUT	|api/milestone/:milestone_id|milestone 수정|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#milestone-%EC%88%98%EC%A0%95)
|DELETE	|api/milestone/:milestone_id|milestone 삭제|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#milestone-%EC%82%AD%EC%A0%9C)

### Milestone - Issue의 Milestone에 대한 CRUD
|메소드|경로|설명|링크|
|-|-|-|-|
|GET	|api/issue/:issue_id/milestone|Issue의 milestone 불러오기|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#issue%EC%9D%98-milestone-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0)
|POST	|api/issue/:issue_id/milestone|Issue에 milestone 추가|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#issue%EC%97%90-milestone-%EC%B6%94%EA%B0%80)
|DELETE	|api/issue/:issue_id/milestone/:milestone_id|Issue의 milestone 삭제|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Milestone-API#issue%EC%97%90-milestone-%EC%82%AD%EC%A0%9C)

## 완료 조건 ✅

- [x] milestone 불러오기
- [x] milestone 생성
- [x] milestone 수정
- [x] milestone 삭제
- [x] Issue의 milestone 불러오기
- [x] Issue에 milestone 추가
- [x] Issue의 milestone 삭제

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
구현을 완료 했으므로 이슈를 닫는다.

**Comment by domino8788** [comment]
위의 커밋을 통해 구현을 완료 했으므로 수정사항이 발생할 때 까지 이슈를 닫는다.
